import type { MachineConfig } from './conveyor-types';

export const CONVEYOR_LAYOUTS: MachineConfig[] = [
  {
    id: 'induction-chute',
    name: 'The Induction Chute',
    theme: 'foundry',
    description: 'A gentle foundry ramp designed to calibrate tilt coordination and belt speed.',
    minPlayers: 2,
    maxPlayers: 3,
    spawnPoint: {
      x: 60,
      y: 90,
      vx: 110,
      vy: 20,
      interval: 3.5,
    },
    targetZone: {
      x: 840,
      y: 440,
      width: 90,
      height: 80,
      label: 'Hopper Alpha',
    },
    hazardY: 570,
    timeLimit: 90,
    targetDeliveries: 10,
    objectPool: ['standard', 'bouncy'],
    defaultPlatforms: [
      { x: 220, y: 220, length: 170, angle: 0.12 },
      { x: 480, y: 310, length: 170, angle: 0.08 },
      { x: 740, y: 400, length: 170, angle: 0.05 },
    ],
    obstacles: [],
  },
  {
    id: 'clockwork-gearworks',
    name: 'Clockwork Gearworks',
    theme: 'gearworks',
    description: 'Rotating brass cogs and delicate glassware require smooth catching angles.',
    minPlayers: 3,
    maxPlayers: 4,
    spawnPoint: {
      x: 70,
      y: 80,
      vx: 130,
      vy: 10,
      interval: 3.2,
    },
    targetZone: {
      x: 850,
      y: 450,
      width: 85,
      height: 75,
      label: 'Receiver Beta',
    },
    hazardY: 570,
    timeLimit: 105,
    targetDeliveries: 12,
    objectPool: ['standard', 'bouncy', 'fragile'],
    defaultPlatforms: [
      { x: 190, y: 190, length: 150, angle: 0.15 },
      { x: 390, y: 280, length: 150, angle: 0.08 },
      { x: 590, y: 360, length: 150, angle: 0.05 },
      { x: 770, y: 430, length: 150, angle: 0.02 },
    ],
    obstacles: [
      { id: 'cog-1', type: 'gear', x: 490, y: 230, radius: 36, rotationSpeed: 2.2 },
      { id: 'cog-2', type: 'gear', x: 290, y: 350, radius: 42, rotationSpeed: -1.8 },
    ],
  },
  {
    id: 'magnetic-foundry',
    name: 'Magnetic Foundry',
    theme: 'cyberpunk',
    description: 'High-mass steel vaults and thermal updrafts test vertical platform adjustments.',
    minPlayers: 4,
    maxPlayers: 5,
    spawnPoint: {
      x: 60,
      y: 70,
      vx: 120,
      vy: 15,
      interval: 3.0,
    },
    targetZone: {
      x: 860,
      y: 430,
      width: 80,
      height: 80,
      label: 'Vault Hopper',
    },
    hazardY: 575,
    timeLimit: 120,
    targetDeliveries: 14,
    objectPool: ['standard', 'heavy', 'bouncy', 'fragile'],
    defaultPlatforms: [
      { x: 170, y: 170, length: 135, angle: 0.18 },
      { x: 330, y: 270, length: 135, angle: 0.1 },
      { x: 490, y: 370, length: 135, angle: -0.05 },
      { x: 650, y: 320, length: 135, angle: 0.12 },
      { x: 790, y: 410, length: 135, angle: 0.04 },
    ],
    obstacles: [
      {
        id: 'updraft-1',
        type: 'wind_tunnel',
        x: 420,
        y: 390,
        width: 110,
        height: 120,
        windForceX: 30,
        windForceY: -420,
      },
    ],
  },
  {
    id: 'rube-goldberg',
    name: 'Rube Goldberg Gauntlet',
    theme: 'rube_goldberg',
    description:
      'The ultimate 6-segment living machine with ticking bombs, gears, and draft chutes.',
    minPlayers: 4,
    maxPlayers: 6,
    spawnPoint: {
      x: 50,
      y: 70,
      vx: 140,
      vy: 10,
      interval: 2.8,
    },
    targetZone: {
      x: 870,
      y: 460,
      width: 75,
      height: 75,
      label: 'Grand Hopper',
    },
    hazardY: 580,
    timeLimit: 135,
    targetDeliveries: 16,
    objectPool: ['standard', 'heavy', 'bouncy', 'fragile', 'explosive'],
    defaultPlatforms: [
      { x: 150, y: 150, length: 120, angle: 0.2 },
      { x: 290, y: 250, length: 120, angle: 0.12 },
      { x: 440, y: 320, length: 120, angle: -0.08 },
      { x: 580, y: 260, length: 120, angle: 0.18 },
      { x: 720, y: 380, length: 120, angle: 0.05 },
      { x: 820, y: 450, length: 120, angle: 0.02 },
    ],
    obstacles: [
      { id: 'gear-main', type: 'gear', x: 360, y: 200, radius: 40, rotationSpeed: 2.4 },
      {
        id: 'updraft-gauntlet',
        type: 'wind_tunnel',
        x: 500,
        y: 280,
        width: 90,
        height: 140,
        windForceX: 20,
        windForceY: -380,
      },
    ],
  },
];

export function getLayoutById(id: string): MachineConfig {
  return CONVEYOR_LAYOUTS.find((l) => l.id === id) ?? CONVEYOR_LAYOUTS[0];
}
