import type { ResourceCard, SecretObjective } from '../types/kingdom-draft.types';

export const SECRET_OBJECTIVES: SecretObjective[] = [
  {
    id: 'imperator',
    title: "Imperator's Bulwark",
    description: 'Construct a mighty bastion: Have at least 3 Defense tiles in your realm.',
    targetCategory: 'defense',
    bonusPoints: 18,
  },
  {
    id: 'renaissance',
    title: 'Cultural Renaissance',
    description: 'Enlighten the populace: Have at least 3 Culture tiles in your realm.',
    targetCategory: 'culture',
    bonusPoints: 18,
  },
  {
    id: 'merchant-prince',
    title: 'Merchant Prince',
    description: 'Amass vast commercial wealth: Have at least 3 Gold tiles in your realm.',
    targetCategory: 'gold',
    bonusPoints: 18,
  },
  {
    id: 'breadbasket',
    title: 'Breadbasket of the Realm',
    description: 'Feed the empire: Have at least 3 Food tiles in your realm.',
    targetCategory: 'food',
    bonusPoints: 18,
  },
  {
    id: 'metropolis',
    title: 'Crowded Metropolis',
    description: 'Attract thriving citizenry: Have at least 3 People tiles in your realm.',
    targetCategory: 'people',
    bonusPoints: 18,
  },
  {
    id: 'imperial-dominion',
    title: 'Imperial Harmony',
    description: 'Balance all realms: Have at least 1 tile from each of the 6 categories.',
    targetCategory: 'diverse',
    bonusPoints: 20,
  },
];

export const KINGDOM_RESOURCE_CARDS: ResourceCard[] = [
  // Land
  {
    id: 'lush-meadow',
    name: 'Lush Meadow',
    category: 'land',
    icon: '🌾',
    basePoints: 2,
    synergyDescription: '+3 pts adjacent to Food',
    synergyPartnerCategory: 'food',
    synergyBonus: 3,
  },
  {
    id: 'river-delta',
    name: 'River Delta',
    category: 'land',
    icon: '🌊',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to Food',
    synergyPartnerCategory: 'food',
    synergyBonus: 3,
  },
  {
    id: 'mountain-ridge',
    name: 'Mountain Ridge',
    category: 'land',
    icon: '⛰️',
    basePoints: 2,
    synergyDescription: '+3 pts adjacent to Defense',
    synergyPartnerCategory: 'defense',
    synergyBonus: 3,
  },
  {
    id: 'sacred-grove',
    name: 'Sacred Grove',
    category: 'land',
    icon: '🌲',
    basePoints: 4,
    synergyDescription: '+4 pts adjacent to Culture',
    synergyPartnerCategory: 'culture',
    synergyBonus: 4,
    isRare: true,
  },

  // People
  {
    id: 'peasant-hamlet',
    name: 'Peasant Hamlet',
    category: 'people',
    icon: '🛖',
    basePoints: 2,
    synergyDescription: '+2 pts adjacent to Land',
    synergyPartnerCategory: 'land',
    synergyBonus: 2,
  },
  {
    id: 'artisan-guild',
    name: 'Artisan Guild',
    category: 'people',
    icon: '⚒️',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to Gold',
    synergyPartnerCategory: 'gold',
    synergyBonus: 3,
  },
  {
    id: 'harbor-town',
    name: 'Harbor Town',
    category: 'people',
    icon: '⛵',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to Food',
    synergyPartnerCategory: 'food',
    synergyBonus: 3,
  },
  {
    id: 'royal-court',
    name: 'Royal Court',
    category: 'people',
    icon: '👑',
    basePoints: 5,
    synergyDescription: '+4 pts adjacent to Culture',
    synergyPartnerCategory: 'culture',
    synergyBonus: 4,
    isRare: true,
  },

  // Food
  {
    id: 'wheat-farm',
    name: 'Wheat Farm',
    category: 'food',
    icon: '🚜',
    basePoints: 2,
    synergyDescription: '+3 pts adjacent to Land',
    synergyPartnerCategory: 'land',
    synergyBonus: 3,
  },
  {
    id: 'orchard-vineyard',
    name: 'Orchard Vineyard',
    category: 'food',
    icon: '🍇',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to Land',
    synergyPartnerCategory: 'land',
    synergyBonus: 3,
  },
  {
    id: 'fishing-wharf',
    name: 'Fishing Wharf',
    category: 'food',
    icon: '🐟',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to People',
    synergyPartnerCategory: 'people',
    synergyBonus: 3,
  },
  {
    id: 'windmill-bakery',
    name: 'Windmill Bakery',
    category: 'food',
    icon: '🥖',
    basePoints: 4,
    synergyDescription: '+3 pts adjacent to Food',
    synergyPartnerCategory: 'food',
    synergyBonus: 3,
    isRare: true,
  },

  // Defense
  {
    id: 'wooden-palisade',
    name: 'Wooden Palisade',
    category: 'defense',
    icon: '🪵',
    basePoints: 2,
    synergyDescription: '+2 pts adjacent to Land',
    synergyPartnerCategory: 'land',
    synergyBonus: 2,
  },
  {
    id: 'watchtower',
    name: 'Watchtower',
    category: 'defense',
    icon: '🏹',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to People',
    synergyPartnerCategory: 'people',
    synergyBonus: 3,
  },
  {
    id: 'stone-fortress',
    name: 'Stone Fortress',
    category: 'defense',
    icon: '🏰',
    basePoints: 4,
    synergyDescription: '+4 pts adjacent to Defense',
    synergyPartnerCategory: 'defense',
    synergyBonus: 4,
  },
  {
    id: 'citadel-keep',
    name: 'Citadel Keep',
    category: 'defense',
    icon: '🛡️',
    basePoints: 6,
    synergyDescription: '+4 pts adjacent to People',
    synergyPartnerCategory: 'people',
    synergyBonus: 4,
    isRare: true,
  },

  // Gold
  {
    id: 'silk-bazaar',
    name: 'Silk Bazaar',
    category: 'gold',
    icon: '🎪',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to People',
    synergyPartnerCategory: 'people',
    synergyBonus: 3,
  },
  {
    id: 'copper-mint',
    name: 'Royal Mint',
    category: 'gold',
    icon: '🪙',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to Gold',
    synergyPartnerCategory: 'gold',
    synergyBonus: 3,
  },
  {
    id: 'gold-mine',
    name: 'Gold Mine',
    category: 'gold',
    icon: '⛏️',
    basePoints: 4,
    synergyDescription: '+4 pts adjacent to Land',
    synergyPartnerCategory: 'land',
    synergyBonus: 4,
  },
  {
    id: 'imperial-treasury',
    name: 'Imperial Treasury',
    category: 'gold',
    icon: '💎',
    basePoints: 6,
    synergyDescription: '+4 pts adjacent to Gold',
    synergyPartnerCategory: 'gold',
    synergyBonus: 4,
    isRare: true,
  },

  // Culture
  {
    id: 'monastery-garden',
    name: 'Monastery Garden',
    category: 'culture',
    icon: '🕯️',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to Land',
    synergyPartnerCategory: 'land',
    synergyBonus: 3,
  },
  {
    id: 'theater-amphitheater',
    name: 'Grand Amphitheater',
    category: 'culture',
    icon: '🎭',
    basePoints: 3,
    synergyDescription: '+3 pts adjacent to People',
    synergyPartnerCategory: 'people',
    synergyBonus: 3,
  },
  {
    id: 'grand-library',
    name: 'Grand Library',
    category: 'culture',
    icon: '📜',
    basePoints: 4,
    synergyDescription: '+4 pts adjacent to Culture',
    synergyPartnerCategory: 'culture',
    synergyBonus: 4,
  },
  {
    id: 'royal-cathedral',
    name: 'Spired Cathedral',
    category: 'culture',
    icon: '⛪',
    basePoints: 6,
    synergyDescription: '+4 pts adjacent to Culture',
    synergyPartnerCategory: 'culture',
    synergyBonus: 4,
    isRare: true,
  },
];
