import type { AuctionItem, ComboSet } from '../types/auction-panic.types';

export const COMBO_SETS: ComboSet[] = [
  {
    id: 'pharaoh-legacy',
    name: "The Pharaoh's Legacy",
    requiredItemIds: ['pharaoh-mask', 'scarab-amulet', 'canopic-jar'],
    bonusPoints: 600,
    description: 'Assemble all 3 sacred relics of the ancient desert kings.',
  },
  {
    id: 'cyberpunk-trove',
    name: 'Cyberpunk Trove',
    requiredItemIds: ['neural-chip', 'plasma-blade', 'quantum-core'],
    bonusPoints: 550,
    description: 'Collect high-end cybernetic hardware from 2099.',
  },
  {
    id: 'masterpiece-vault',
    name: 'Masterpiece Vault',
    requiredItemIds: ['mona-sketch', 'golden-chalice', 'baroque-frame'],
    bonusPoints: 500,
    description: 'Curate a trio of European renaissance museum treasures.',
  },
  {
    id: 'oddity-cabinet',
    name: 'Curio Cabinet',
    requiredItemIds: ['crystal-skull', 'mermaid-fossil', 'mystic-orb'],
    bonusPoints: 450,
    description: 'Gather legendary supernatural specimens from the occult fringe.',
  },
];

export const AUCTION_ITEMS_CATALOG: AuctionItem[] = [
  // Antiquities
  {
    id: 'pharaoh-mask',
    name: 'Gilded Burial Mask',
    category: 'antiquities',
    rarity: 'legendary',
    hint: 'Gleams under torchlight; heavy solid gold with lapis lazuli eyes.',
    crypticDescription: 'Unearthed from the Valley of the Kings. Weighs 12 kilograms of pure gold.',
    baseValue: 950,
    isJunk: false,
    comboSetId: 'pharaoh-legacy',
    icon: '👑',
  },
  {
    id: 'scarab-amulet',
    name: 'Obsidian Scarab Amulet',
    category: 'antiquities',
    rarity: 'rare',
    hint: 'Carved beetle amulet pulsing with faint mystical energy.',
    crypticDescription:
      'Anointed by priests during the third dynasty. Highly sought by occultists.',
    baseValue: 550,
    isJunk: false,
    comboSetId: 'pharaoh-legacy',
    icon: '🪲',
  },
  {
    id: 'canopic-jar',
    name: 'Alabaster Canopic Jar',
    category: 'antiquities',
    rarity: 'uncommon',
    hint: 'A sealed stone jar adorned with a falcon head stopper.',
    crypticDescription: 'Preserved royal urn containing ancient perfumes and resins.',
    baseValue: 400,
    isJunk: false,
    comboSetId: 'pharaoh-legacy',
    icon: '🏺',
  },

  // Galactic Tech
  {
    id: 'quantum-core',
    name: 'Sub-Zero Quantum Core',
    category: 'galactic-tech',
    rarity: 'legendary',
    hint: 'Humming cylindrical reactor cell venting cryogenic vapor.',
    crypticDescription: 'Power source capable of warping local spacetime. Extremely valuable.',
    baseValue: 1000,
    isJunk: false,
    comboSetId: 'cyberpunk-trove',
    icon: '🔮',
  },
  {
    id: 'plasma-blade',
    name: 'Overcharged Plasma Blade',
    category: 'galactic-tech',
    rarity: 'rare',
    hint: 'Chrome hilt emitting a blinding ionizing beam.',
    crypticDescription: 'Military-grade prototype from an orbital black-site laboratory.',
    baseValue: 600,
    isJunk: false,
    comboSetId: 'cyberpunk-trove',
    icon: '⚡',
  },
  {
    id: 'neural-chip',
    name: 'Cortex Neural Interface',
    category: 'galactic-tech',
    rarity: 'uncommon',
    hint: 'Microscopic gold wire array encased in synthetic diamond.',
    crypticDescription: 'Direct brain-computer link used by high-frequency market operators.',
    baseValue: 420,
    isJunk: false,
    comboSetId: 'cyberpunk-trove',
    icon: '💾',
  },

  // Fine Art
  {
    id: 'mona-sketch',
    name: 'Original Charcoal Study',
    category: 'fine-art',
    rarity: 'legendary',
    hint: 'Framed parchment with delicate hand-drawn enigmatic smile.',
    crypticDescription:
      'Lost preliminary study by an Italian polymath. Verified by top auction houses.',
    baseValue: 900,
    isJunk: false,
    comboSetId: 'masterpiece-vault',
    icon: '🎨',
  },
  {
    id: 'golden-chalice',
    name: 'Imperial Coronation Chalice',
    category: 'fine-art',
    rarity: 'rare',
    hint: 'Chased goblet encrusted with emeralds and rubies.',
    crypticDescription: 'Used in 16th-century European coronation ceremonies.',
    baseValue: 620,
    isJunk: false,
    comboSetId: 'masterpiece-vault',
    icon: '🏆',
  },
  {
    id: 'baroque-frame',
    name: 'Hand-Carved Gilt Frame',
    category: 'fine-art',
    rarity: 'uncommon',
    hint: 'Opulent wooden frame with ornate floral filigree.',
    crypticDescription: 'Empty 18th-century Venetian frame valued for its pristine gold leaf.',
    baseValue: 380,
    isJunk: false,
    comboSetId: 'masterpiece-vault',
    icon: '🖼️',
  },

  // Oddities
  {
    id: 'crystal-skull',
    name: 'Prismatic Quartz Skull',
    category: 'oddities',
    rarity: 'rare',
    hint: 'Translucent skull refracting rainbow beams onto the gallery walls.',
    crypticDescription: 'Carved against the grain of natural quartz with impossible precision.',
    baseValue: 650,
    isJunk: false,
    comboSetId: 'oddity-cabinet',
    icon: '💀',
  },
  {
    id: 'mermaid-fossil',
    name: 'Fiji Mummified Specimen',
    category: 'oddities',
    rarity: 'uncommon',
    hint: 'Bizarre chimera skeleton preserved in a glass dome.',
    crypticDescription:
      'Victorian carnival spectacle of ape and fish taxidermy. Rare novelty value.',
    baseValue: 430,
    isJunk: false,
    comboSetId: 'oddity-cabinet',
    icon: '🧜',
  },
  {
    id: 'mystic-orb',
    name: 'Swirling Aether Orb',
    category: 'oddities',
    rarity: 'uncommon',
    hint: 'Heavy sphere containing bioluminescent mist.',
    crypticDescription:
      'Victorian parlor curiosity filled with phosphorescent deep-sea plankton oil.',
    baseValue: 390,
    isJunk: false,
    comboSetId: 'oddity-cabinet',
    icon: '🧿',
  },

  // Standalone Treasures
  {
    id: 'pirate-chest',
    name: 'Sunken Doubloon Chest',
    category: 'antiquities',
    rarity: 'legendary',
    hint: 'Barnacle-encrusted ironbound chest with a heavy padlock.',
    crypticDescription: 'Recovered from a Caribbean galleon. Bursting with silver and gold coins.',
    baseValue: 850,
    isJunk: false,
    icon: '📦',
  },
  {
    id: 'diamond-watch',
    name: 'Tourbillon Pocket Chronometer',
    category: 'fine-art',
    rarity: 'rare',
    hint: 'Intricate ticking timepiece featuring diamond escapement.',
    crypticDescription: 'Swiss master craft. Accurate to one second per millennium.',
    baseValue: 700,
    isJunk: false,
    icon: '⏱️',
  },

  // Cursed & Dangerous Items
  {
    id: 'haunted-doll',
    name: 'Porcelain Victorian Doll',
    category: 'oddities',
    rarity: 'cursed',
    hint: 'Antique porcelain face with glass eyes that seem to track you.',
    crypticDescription: 'Previous owners reported chilly breezes and unexplained missing coins.',
    baseValue: -250,
    isJunk: false,
    isCursed: true,
    penalty: 250,
    icon: '🪆',
  },
  {
    id: 'gremlin-crate',
    name: 'Scratched Wooden Shipping Crate',
    category: 'oddities',
    rarity: 'cursed',
    hint: 'Something inside is violently shaking the box and growling.',
    crypticDescription: 'Whatever was inside chewed through the packaging and caused havoc.',
    baseValue: -300,
    isJunk: false,
    isCursed: true,
    penalty: 300,
    icon: '📦',
  },

  // Junk Items
  {
    id: 'rusty-can',
    name: 'Vintage Rusty Tin Can',
    category: 'junk',
    rarity: 'common',
    hint: 'A cylindrical container wrapped in faded, peeling tin foil.',
    crypticDescription: 'It was just an empty soup can from 1984. Total junk.',
    baseValue: 15,
    isJunk: true,
    icon: '🥫',
  },
  {
    id: 'broken-toaster',
    name: 'Two-Slice Retro Toaster',
    category: 'junk',
    rarity: 'common',
    hint: 'Metallic kitchen appliance with vintage chrome sheen.',
    crypticDescription: 'Missing heating coils and power cord. Worthless junk.',
    baseValue: 10,
    isJunk: true,
    icon: '🍞',
  },
  {
    id: 'moldy-sandwich',
    name: 'Petrified Deli Sub',
    category: 'junk',
    rarity: 'common',
    hint: 'Wrapped in brown paper parchment labeled "Special Delivery".',
    crypticDescription: 'A six-month-old meatball sub that turned green. Negative appraisal value.',
    baseValue: -50,
    isJunk: true,
    icon: '🥪',
  },
  {
    id: 'deflated-balloon',
    name: 'Latex Birthday Relic',
    category: 'junk',
    rarity: 'common',
    hint: 'Wrinkled colorful rubber membrane with attached string.',
    crypticDescription: 'A sad deflated helium balloon from someone elses party.',
    baseValue: 5,
    isJunk: true,
    icon: '🎈',
  },
  {
    id: 'loose-screws',
    name: 'Mystery Jar of Hardware',
    category: 'junk',
    rarity: 'common',
    hint: 'Heavy glass jar rattling with miscellaneous metallic pieces.',
    crypticDescription: 'Assorted mismatched wood screws and washers from a garage cleanup.',
    baseValue: 20,
    isJunk: true,
    icon: '🔩',
  },
];
