import type { HoneycombPuzzle } from '../types/spelling-bee.types';

export const HONEYCOMB_PUZZLES: HoneycombPuzzle[] = [
  {
    id: 'bee-1',
    centerLetter: 'P',
    outerLetters: ['A', 'C', 'E', 'I', 'R', 'T'],
    pangrams: ['PRACTICE', 'APPRECIATE', 'PARTICIPATE', 'PRECIPITATE'],
    validWords: [
      'PACE',
      'PACT',
      'PAIR',
      'PALE',
      'PART',
      'PATE',
      'PEAR',
      'PEAT',
      'PERT',
      'PIER',
      'PITA',
      'PRAT',
      'PRICE',
      'RAPT',
      'REAP',
      'RIPE',
      'TRAP',
      'TRIP',
      'PARTER',
      'PIRATE',
      'PRACTICE',
      'RECIPROCATE',
      'APPRECIATE',
      'PARTICIPATE',
      'PRECIPITATE',
      'CARPET',
      'CRATER',
      'CRICKET',
      'PATER',
      'PIPET',
      'PIRATIC',
      'PRANCER',
      'PROTECT',
      'REPAIR',
    ],
    maxScore: 160,
  },
  {
    id: 'bee-2',
    centerLetter: 'B',
    outerLetters: ['E', 'L', 'N', 'O', 'T', 'U'],
    pangrams: ['BLUEBONNET', 'UNBOTTLE'],
    validWords: [
      'BEEN',
      'BEET',
      'BELL',
      'BELT',
      'BENT',
      'BLOT',
      'BLUNT',
      'BOLE',
      'BONE',
      'BOTE',
      'LENTO',
      'LOBE',
      'LUTE',
      'NOBLE',
      'NOTE',
      'TENON',
      'TENT',
      'TOLU',
      'TONE',
      'TUBE',
      'TUNE',
      'BEETLE',
      'BONNET',
      'BUTTON',
      'LETTUCE',
      'LOBELET',
      'BLUEBONNET',
      'UNBOTTLE',
      'BOTTLE',
      'BOUNTY',
      'BULLET',
      'BLESS',
      'BLUNTLY',
    ],
    maxScore: 135,
  },
  {
    id: 'bee-3',
    centerLetter: 'G',
    outerLetters: ['A', 'I', 'L', 'M', 'N', 'O'],
    pangrams: ['GLOAMING', 'AGNOMINAL', 'ANGLOMANIA'],
    validWords: [
      'GAIN',
      'GALA',
      'GANG',
      'GLAM',
      'GLIA',
      'GLIM',
      'GOAL',
      'GONG',
      'GOWN',
      'GRAM',
      'GRIM',
      'GRIN',
      'AGING',
      'ALIGN',
      'ALONG',
      'AMONG',
      'ANALOG',
      'GAMING',
      'GLOAM',
      'GLOAMING',
      'AGNOMINAL',
      'ANGLOMANIA',
      'MAGMA',
      'MANGO',
      'MARGIN',
      'MONGL',
    ],
    maxScore: 140,
  },
  {
    id: 'bee-4',
    centerLetter: 'T',
    outerLetters: ['C', 'E', 'I', 'M', 'N', 'O'],
    pangrams: ['COMMITMENT', 'CENTIMO', 'COMMITTEEMEN'],
    validWords: [
      'CENT',
      'CITE',
      'COOT',
      'EMIT',
      'INTO',
      'ITEM',
      'MINT',
      'MITE',
      'MOOT',
      'NOTE',
      'OMEN',
      'OMIT',
      'ONCE',
      'TENT',
      'TIME',
      'TINE',
      'TONE',
      'TOOT',
      'CEMENT',
      'COMMIT',
      'INCOME',
      'INTENT',
      'MINCE',
      'NOTICE',
      'COMMITMENT',
      'CENTIMO',
      'COMMITTEEMEN',
    ],
    maxScore: 145,
  },
  {
    id: 'bee-5',
    centerLetter: 'C',
    outerLetters: ['A', 'D', 'E', 'I', 'N', 'T'],
    pangrams: ['ACCIDENT', 'ACCIDENTED', 'ACTINIDE'],
    validWords: [
      'ACID',
      'ACNE',
      'CANE',
      'CANT',
      'CARD',
      'CART',
      'CEDE',
      'CINE',
      'CITE',
      'DACE',
      'DICE',
      'ICED',
      'INCA',
      'NICE',
      'TACT',
      'TACE',
      'ACCENT',
      'ACETIC',
      'ACTIAN',
      'CADENT',
      'CANDID',
      'CANINE',
      'CATENA',
      'DETICT',
      'INDICE',
      'ACCIDENT',
    ],
    maxScore: 150,
  },
  {
    id: 'bee-6',
    centerLetter: 'P',
    outerLetters: ['A', 'H', 'I', 'N', 'O', 'T'],
    pangrams: ['PHONATION', 'ANTIPHON', 'PHOTINIA'],
    validWords: [
      'PATH',
      'PAWN',
      'PINT',
      'PION',
      'PITA',
      'PITH',
      'PONY',
      'POOH',
      'POOP',
      'POTTO',
      'PATIO',
      'PHONO',
      'PINON',
      'PINTO',
      'PIPIT',
      'PITON',
      'POINT',
      'POTION',
      'PYTHON',
      'ANTIPHON',
      'PHONATION',
      'PHOTINIA',
      'PHOTO',
      'PIANO',
      'TOPAZ',
    ],
    maxScore: 130,
  },
];

export function getRandomPuzzle(): HoneycombPuzzle {
  const index = Math.floor(Math.random() * HONEYCOMB_PUZZLES.length);
  return HONEYCOMB_PUZZLES[index];
}

export function getDailyPuzzle(dateString?: string): HoneycombPuzzle {
  const dateKey = dateString || new Date().toISOString().slice(0, 10);
  let hash = 0;
  for (let i = 0; i < dateKey.length; i += 1) {
    hash = (hash << 5) - hash + dateKey.charCodeAt(i);
    hash |= 0;
  }
  const index = Math.abs(hash) % HONEYCOMB_PUZZLES.length;
  return HONEYCOMB_PUZZLES[index];
}
