import type { StoryPrompt } from '../types/one-word-story.types';

export const STORY_PROMPTS: StoryPrompt[] = [
  {
    id: 'haunted-arcade',
    title: 'The Haunted Arcade Machine',
    genre: 'horror',
    starterPhrase: 'Deep inside the dusty arcade basement, the coin slot clicked and',
    challengeWords: ['ghost', 'joystick', 'glitch', 'midnight'],
  },
  {
    id: 'pizza-planet',
    title: 'Intergalactic Pizza Delivery',
    genre: 'sci-fi',
    starterPhrase: 'Commander Zog strapped in his rocket pack, determined to deliver',
    challengeWords: ['cheese', 'warp', 'nebula', 'crust'],
  },
  {
    id: 'royal-duck',
    title: 'The Prince and the Golden Duck',
    genre: 'fantasy',
    starterPhrase: 'Before the grand council could speak, Sir Reginald gently lifted',
    challengeWords: ['quack', 'crown', 'feather', 'pond'],
  },
  {
    id: 'neon-detective',
    title: 'Midnight in Cyber District 9',
    genre: 'cyberpunk',
    starterPhrase: 'Rain poured over glowing holo-billboards as the detective checked',
    challengeWords: ['cyber', 'shadow', 'code', 'neon'],
  },
  {
    id: 'museum-heist',
    title: 'The Great Museum Catastrophe',
    genre: 'mystery',
    starterPhrase: 'The laser alarm went silent, revealing that the mastermind had replaced',
    challengeWords: ['diamond', 'banana', 'escape', 'disguise'],
  },
  {
    id: 'talking-fridge',
    title: 'The Refrigerator That Knew Too Much',
    genre: 'comedy',
    starterPhrase: 'At three in the morning, the butter compartment whispered',
    challengeWords: ['mayo', 'secrets', 'leftovers', 'freeze'],
  },
  {
    id: 'dragon-barista',
    title: 'The Coffee-Breathing Dragon',
    genre: 'fantasy',
    starterPhrase: 'With a roar of boiling steam, the ancient beast served',
    challengeWords: ['latte', 'espresso', 'cinnamon', 'flame'],
  },
  {
    id: 'time-travel-toast',
    title: 'The Chrono-Toaster Paradox',
    genre: 'sci-fi',
    starterPhrase: 'When the timer reached zero, the toasted bagel suddenly vanished',
    challengeWords: ['quantum', 'butter', 'future', 'vortex'],
  },
  {
    id: 'spooky-attic',
    title: 'Whispers Beneath the Floorboards',
    genre: 'horror',
    starterPhrase: 'In the moonlight, the ancient wooden chest creaked open and',
    challengeWords: ['skeleton', 'creak', 'candle', 'key'],
  },
  {
    id: 'superhero-dog',
    title: 'Captain Bark to the Rescue',
    genre: 'comedy',
    starterPhrase: 'Wearing a bright red cape, the tiny Chihuahua boldly challenged',
    challengeWords: ['bone', 'villain', 'bark', 'hero'],
  },
];

export const BOT_VOCABULARY: Record<string, string[]> = {
  poet: [
    'whispering',
    'moonlight',
    'gently',
    'crimson',
    'shadows',
    'melancholy',
    'radiance',
    'eternal',
    'sorrow',
    'blossom',
    'starlight',
    'drifting',
  ],
  chaotic: [
    'EXPLODED!',
    'suddenly',
    'screaming',
    'catastrophic',
    'yeet',
    'bananas',
    'chaos',
    'wildly',
    'laser',
    'BOOM,',
    'disaster',
    'unleashed',
  ],
  dramatic: [
    'betrayed',
    'destiny',
    'forever.',
    'gasping,',
    'revealed',
    'vengeance',
    'shockingly,',
    'truth',
    'unforgivable',
    'doomed',
    'fate',
    'silence.',
  ],
  philosopher: [
    'perhaps',
    'existence',
    'meaning',
    'pondered',
    'truthfully,',
    'why',
    'illusion',
    'inevitably',
    'reflecting',
    'therefore',
    'reality',
    'questioning',
  ],
};

export const COMMON_CONNECTORS: string[] = [
  'and',
  'then',
  'suddenly',
  'because',
  'while',
  'although',
  'towards',
  'into',
  'without',
  'through',
  'beside',
  'under',
  'over',
  'despite',
];
