export const GameTags = {
  // Core & Player Modes
  M_P: 'Multiplayer',
  V_C: 'Voice Chat',
  P: 'Party',
  S: 'Solo',
  PZ: 'Puzzle',
  ST: 'Strategy',
  C: 'Classic',
  HS: 'High Score',
  T: 'Tactile',
  LP: 'Local Play',
  AI: 'AI Opponent',
  PH: 'Physics',
  CO: 'Cooperative',
  SD: 'Social Deception',
  WP: 'Word Puzzle',
  B: 'Board',
  A: 'Arcade',
  TB: 'Turn-based',
  ACT: 'Action',
  LOG: 'Logic',
  MEM: 'Memory',
  SR: 'Speedrun',
  TD: '3D',
  DICE: 'Dice',

  // Controls & Accessibility
  POWER_UPS: 'Power-ups',
  TOUCH_READY: 'Touch Ready',
  KEYBOARD_READY: 'Keyboard Ready',
  VOICE_ESSENTIAL: 'Voice-Essential',
  QUICK_PLAY: 'Quick Play',

  // Gameplay Themes & Mechanics
  ADVENTURE: 'Adventure',
  AIM: 'Aim',
  ARCANE: 'Arcane',
  BALL_PHYSICS: 'Ball Physics',
  BASKETBALL: 'Basketball',
  BLUFFING: 'Bluffing',
  BOSS_FIGHT: 'Boss Fight',
  BOTS: 'Bots',
  BOW: 'Bow',
  BRAIN_TRAINING: 'Brain Training',
  CARD_DRAFTING: 'Card Drafting',
  CLIMB: 'Climb',
  COMBAT: 'Combat',
  DRIVING: 'Driving',
  ENDLESS: 'Endless',
  GRANDMASTER: 'Grandmaster',
  GRAVITY_GRID: 'Gravity Grid',
  GRID_BUILDING: 'Grid Building',
  JUMP: 'Jump',
  MULTIPLAYER_READY: 'Multiplayer Ready',
  NINJA: 'Ninja',
  NOSTALGIA: 'Nostalgia',
  ONLINE_1V1: 'Online 1v1',
  ONLINE_MULTIPLAYER: 'Online Multiplayer',
  ONLINE_RACE: 'Online Race',
  PARKOUR: 'Parkour',
  PARRY: 'Parry',
  PLATFORMER: 'Platformer',
  PRECISION: 'Precision',
  RACING: 'Racing',
  REFLEXES: 'Reflexes',
  RETRO: 'Retro',
  RISK: 'Risk',
  SHADOW: 'Shadow',
  SHOOTER: 'Shooter',
  SOLITAIRE: 'Solitaire',
  SPEED: 'Speed',
  SPORTS: 'Sports',
  STEALTH: 'Stealth',
  SURVIVAL: 'Survival',
  SWORD: 'Sword',
  UPGRADES: 'Upgrades',
  VERTICAL: 'Vertical',

  // Capacities & Levels
  PLAYERS_2_4: '2-4 Players',
  PLAYERS_2_6: '2-6 Players',
  LEVELS_7: '7 Levels',
} as const;

export type GameTags = (typeof GameTags)[keyof typeof GameTags];
