import type { Achievement } from '@playdeck/game-types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_win',
    title: 'First Victory',
    description: 'Claim your very first win in any game on PlayDeck.',
    category: 'general',
    icon: '🏆',
    xpReward: 100,
    maxProgress: 1,
  },
  {
    id: 'game_explorer',
    title: 'Genre Explorer',
    description: 'Play games across at least 3 distinct game categories.',
    category: 'general',
    icon: '🧭',
    xpReward: 150,
    maxProgress: 3,
  },
  {
    id: 'arcade_enthusiast',
    title: 'Arcade Enthusiast',
    description: 'Play 10 sessions of arcade classics or action games.',
    category: 'arcade',
    icon: '🕹️',
    xpReward: 200,
    maxProgress: 10,
  },
  {
    id: 'puzzle_prodigy',
    title: 'Puzzle Prodigy',
    description: 'Win 5 puzzle or brain teaser challenges.',
    category: 'puzzle',
    icon: '🧩',
    xpReward: 250,
    maxProgress: 5,
  },
  {
    id: 'strategic_mind',
    title: 'Strategic Mind',
    description: 'Win 5 strategy, tactical, or board games.',
    category: 'strategy',
    icon: '♟️',
    xpReward: 250,
    maxProgress: 5,
  },
  {
    id: 'card_sharp',
    title: 'Card Sharp',
    description: 'Play 5 card or social shedding game sessions.',
    category: 'card',
    icon: '🃏',
    xpReward: 150,
    maxProgress: 5,
  },
  {
    id: 'high_roller',
    title: 'High Roller',
    description: 'Record a single-game score of 1,000 points or higher.',
    category: 'general',
    icon: '💎',
    xpReward: 300,
    maxProgress: 1000,
  },
  {
    id: 'hot_streak',
    title: 'Hot Streak',
    description: 'Win 3 game sessions in a row without a defeat.',
    category: 'general',
    icon: '🔥',
    xpReward: 350,
    maxProgress: 3,
  },
  {
    id: 'century_club',
    title: 'Century Club',
    description: 'Play a cumulative total of 100 game sessions.',
    category: 'general',
    icon: '👑',
    xpReward: 500,
    maxProgress: 100,
  },
  {
    id: 'deck_veteran',
    title: 'Deck Veteran',
    description: 'Reach Player Level 5 through accumulated match XP.',
    category: 'general',
    icon: '🎖️',
    xpReward: 400,
    maxProgress: 5,
  },
  {
    id: 'night_owl',
    title: 'Night Owl',
    description: 'Complete a match between 10 PM and 4 AM local time.',
    category: 'general',
    icon: '🦉',
    xpReward: 100,
    maxProgress: 1,
  },
  {
    id: 'custom_identity',
    title: 'Fresh Identity',
    description: 'Customize your player handle or chosen arcade avatar.',
    category: 'general',
    icon: '✨',
    xpReward: 50,
    maxProgress: 1,
  },
];
