import type { IdentityCategory, IdentityItem } from '../types/who-am-i.types';

export const IDENTITIES_DATABASE: IdentityItem[] = [
  // Animals
  {
    id: 'penguin',
    name: 'Penguin',
    category: 'animals',
    icon: '🐧',
    description: 'A tuxedo-wearing, flightless Antarctic bird that waddles and slides on ice.',
    isAlive: true,
    isHuman: false,
    isFictional: false,
    isObject: false,
    canFly: false,
  },
  {
    id: 'giraffe',
    name: 'Giraffe',
    category: 'animals',
    icon: '🦒',
    description: 'The tallest mammal on Earth with a long neck and spotted yellow coat.',
    isAlive: true,
    isHuman: false,
    isFictional: false,
    isObject: false,
    canFly: false,
  },
  {
    id: 'lion',
    name: 'Lion',
    category: 'animals',
    icon: '🦁',
    description: 'The king of the jungle with a majestic golden mane.',
    isAlive: true,
    isHuman: false,
    isFictional: false,
    isObject: false,
    canFly: false,
  },
  {
    id: 'eagle',
    name: 'Bald Eagle',
    category: 'animals',
    icon: '🦅',
    description: 'A fierce raptor with sharp eyesight and soaring wings.',
    isAlive: true,
    isHuman: false,
    isFictional: false,
    isObject: false,
    canFly: true,
  },
  {
    id: 'dolphin',
    name: 'Dolphin',
    category: 'animals',
    icon: '🐬',
    description: 'An acrobatic, playful marine mammal known for high intelligence.',
    isAlive: true,
    isHuman: false,
    isFictional: false,
    isObject: false,
    canFly: false,
  },
  {
    id: 'kangaroo',
    name: 'Kangaroo',
    category: 'animals',
    icon: '🦘',
    description: 'An Australian marsupial with powerful hind legs and a baby pouch.',
    isAlive: true,
    isHuman: false,
    isFictional: false,
    isObject: false,
    canFly: false,
  },

  // Movie Characters
  {
    id: 'sherlock-holmes',
    name: 'Sherlock Holmes',
    category: 'movie-characters',
    icon: '🕵️‍♂️',
    description: 'A legendary master of deductive logic who lives on Baker Street.',
    isAlive: false,
    isHuman: true,
    isFictional: true,
    isObject: false,
  },
  {
    id: 'darth-vader',
    name: 'Darth Vader',
    category: 'movie-characters',
    icon: '🦹‍♂️',
    description: 'A fallen Jedi Lord cloaked in black armor wielding a crimson lightsaber.',
    isAlive: false,
    isHuman: true,
    isFictional: true,
    isObject: false,
  },
  {
    id: 'harry-potter',
    name: 'Harry Potter',
    category: 'movie-characters',
    icon: '⚡',
    description: 'The Boy Who Lived with a lightning bolt scar, round spectacles, and wand.',
    isAlive: false,
    isHuman: true,
    isFictional: true,
    isObject: false,
  },
  {
    id: 'spider-man',
    name: 'Spider-Man',
    category: 'movie-characters',
    icon: '🕷️',
    description: 'Friendly neighborhood wall-crawler with web-shooters and spider-sense.',
    isAlive: false,
    isHuman: true,
    isFictional: true,
    isObject: false,
  },
  {
    id: 'shrek',
    name: 'Shrek',
    category: 'movie-characters',
    icon: '🧅',
    description: 'A lovable green ogre who loves his swamp and compares onions to layers.',
    isAlive: false,
    isHuman: false,
    isFictional: true,
    isObject: false,
  },
  {
    id: 'jack-sparrow',
    name: 'Captain Jack Sparrow',
    category: 'movie-characters',
    icon: '🏴‍☠️',
    description: 'An eccentric pirate captain who loves rum and compasses that do not point north.',
    isAlive: false,
    isHuman: true,
    isFictional: true,
    isObject: false,
  },

  // Famous People
  {
    id: 'albert-einstein',
    name: 'Albert Einstein',
    category: 'famous-people',
    icon: '⚛️',
    description:
      'Theoretical physicist with wild hair who formulated the theory of relativity (E=mc²).',
    isAlive: false,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },
  {
    id: 'leonardo-da-vinci',
    name: 'Leonardo da Vinci',
    category: 'famous-people',
    icon: '🎨',
    description: 'Renaissance polymath who painted the Mona Lisa and sketched flying machines.',
    isAlive: false,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },
  {
    id: 'cleopatra',
    name: 'Cleopatra',
    category: 'historical-figures',
    icon: '👑',
    description: 'The last active ruler of the Ptolemaic Kingdom of Egypt.',
    isAlive: false,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },
  {
    id: 'marie-curie',
    name: 'Marie Curie',
    category: 'historical-figures',
    icon: '🧪',
    description:
      'Pioneering chemist who conducted research on radioactivity and won two Nobel Prizes.',
    isAlive: false,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },
  {
    id: 'william-shakespeare',
    name: 'William Shakespeare',
    category: 'historical-figures',
    icon: '📜',
    description: 'The English Bard who penned Hamlet, Romeo and Juliet, and dozens of sonnets.',
    isAlive: false,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },
  {
    id: 'neil-armstrong',
    name: 'Neil Armstrong',
    category: 'historical-figures',
    icon: '👨‍🚀',
    description: 'The first person to set foot on the moon with Apollo 11.',
    isAlive: false,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },

  // Professions
  {
    id: 'astronaut',
    name: 'Astronaut',
    category: 'professions',
    icon: '🚀',
    description: 'A space voyager trained to fly outside Earth’s atmosphere in zero gravity.',
    isAlive: true,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },
  {
    id: 'firefighter',
    name: 'Firefighter',
    category: 'professions',
    icon: '🚒',
    description:
      'A brave rescuer in yellow turnout gear who battles blazes with high-pressure hoses.',
    isAlive: true,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },
  {
    id: 'chef',
    name: 'Master Chef',
    category: 'professions',
    icon: '🍳',
    description:
      'A culinary artist in a tall toque blanche who commands a sizzling restaurant kitchen.',
    isAlive: true,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },
  {
    id: 'detective',
    name: 'Private Detective',
    category: 'professions',
    icon: '🔍',
    description: 'An investigator in a trench coat tracking footprints with a magnifying glass.',
    isAlive: true,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },
  {
    id: 'pilot',
    name: 'Airline Pilot',
    category: 'professions',
    icon: '✈️',
    description: 'An aviator navigating passenger jet airliners at 35,000 feet.',
    isAlive: true,
    isHuman: true,
    isFictional: false,
    isObject: false,
  },

  // Objects & Food
  {
    id: 'pizza',
    name: 'Pepperoni Pizza',
    category: 'objects',
    icon: '🍕',
    description: 'A hot triangular slice of baked crust loaded with mozzarella and melted cheese.',
    isAlive: false,
    isHuman: false,
    isFictional: false,
    isObject: true,
  },
  {
    id: 'smartphone',
    name: 'Smartphone',
    category: 'objects',
    icon: '📱',
    description: 'A pocket glass rectangle containing apps, camera, and the internet.',
    isAlive: false,
    isHuman: false,
    isFictional: false,
    isObject: true,
  },
  {
    id: 'toaster',
    name: 'Toaster',
    category: 'objects',
    icon: '🍞',
    description: 'A kitchen appliance with glowing heating coils that pops sliced bread up brown.',
    isAlive: false,
    isHuman: false,
    isFictional: false,
    isObject: true,
  },
  {
    id: 'guitar',
    name: 'Electric Guitar',
    category: 'objects',
    icon: '🎸',
    description: 'A six-string musical instrument plugged into an amplifier to rock stadiums.',
    isAlive: false,
    isHuman: false,
    isFictional: false,
    isObject: true,
  },
  {
    id: 'clock',
    name: 'Grandfather Clock',
    category: 'objects',
    icon: '🕰️',
    description: 'A tall wooden pendulum clock ticking seconds and chiming on the hour.',
    isAlive: false,
    isHuman: false,
    isFictional: false,
    isObject: true,
  },
];

export function getIdentitiesForCategory(category: IdentityCategory): IdentityItem[] {
  if (category === 'all') return IDENTITIES_DATABASE;
  return IDENTITIES_DATABASE.filter((i) => i.category === category);
}
