export type CrosswordTheme = 'science' | 'geography' | 'general' | 'sports' | 'pop-culture';

export type CrosswordDifficulty = 'easy' | 'medium' | 'hard';

export type CrosswordDirection = 'across' | 'down';

export interface RawCrosswordClue {
  id: string;
  number: number;
  direction: CrosswordDirection;
  row: number;
  col: number;
  answer: string;
  text: string;
}

export interface CrosswordPuzzleDefinition {
  id: string;
  title: string;
  theme: CrosswordTheme;
  difficulty: CrosswordDifficulty;
  rows: number;
  cols: number;
  clues: RawCrosswordClue[];
}

export const CROSSWORD_PUZZLES: CrosswordPuzzleDefinition[] = [
  // ==========================================
  // EASY TIER (4x4 Mini Puzzles)
  // ==========================================
  {
    id: 'science-easy-1',
    title: 'Cosmic Sparks',
    theme: 'science',
    difficulty: 'easy',
    rows: 4,
    cols: 4,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 1,
        answer: 'FIT',
        text: 'Well adapted to an ecological niche in evolution',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 1,
        col: 0,
        answer: 'WIRE',
        text: 'Conductive metal filament carrying electrical current',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'IRON',
        text: 'Magnetic transition element with atomic number 26 (Fe)',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 3,
        col: 0,
        answer: 'TEN',
        text: 'Base of the universal decimal metric system',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 1,
        col: 0,
        answer: 'WIT',
        text: 'Quick inventive intelligence and cognitive agility',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 1,
        answer: 'FIRE',
        text: 'Exothermic chemical oxidation creating heat and light',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'IRON',
        text: 'Dense element synthesized inside dying giant stars',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 3,
        answer: 'TEN',
        text: 'Spacetime dimension count in superstring theory',
      },
    ],
  },
  {
    id: 'geography-easy-1',
    title: 'Oceans & Stars',
    theme: 'geography',
    difficulty: 'easy',
    rows: 4,
    cols: 4,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 1,
        answer: 'SEA',
        text: 'Vast continuous body of marine saltwater',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 1,
        col: 0,
        answer: 'STAR',
        text: 'Polaris or nocturnal guide for maritime navigation',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'EAST',
        text: 'Compass cardinal bearing toward the morning sunrise',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 3,
        col: 0,
        answer: 'ART',
        text: 'Ancient petroglyphs and cultural cave paintings',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 1,
        col: 0,
        answer: 'SEA',
        text: 'Mediterranean or Caribbean coastal waters',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 1,
        answer: 'STAR',
        text: 'Luminous stellar furnace lighting the heavens',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'EAST',
        text: 'Orient direction pointing rightward on globe maps',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 3,
        answer: 'ART',
        text: 'Traditional folk crafts and museum artifacts',
      },
    ],
  },
  {
    id: 'general-easy-1',
    title: 'Everyday Enigmas',
    theme: 'general',
    difficulty: 'easy',
    rows: 4,
    cols: 4,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 1,
        answer: 'HIT',
        text: 'Chart-topping musical success or accurate target strike',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 1,
        col: 0,
        answer: 'HASH',
        text: 'Cryptographic digest function or skillet potato dish',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'ISLE',
        text: 'Small peaceful tract of land encircled by water',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 3,
        col: 0,
        answer: 'THE',
        text: 'Most frequently uttered definite article in English',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 1,
        col: 0,
        answer: 'HIT',
        text: 'Smash box-office triumph or bullseye impact',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 1,
        answer: 'HASH',
        text: 'One-way algorithm converting strings to fixed hex',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'ISLE',
        text: 'Miniature tropical coral key or remote haven',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 3,
        answer: 'THE',
        text: 'Grammatical specifier introducing nouns',
      },
    ],
  },
  {
    id: 'sports-easy-1',
    title: 'Match Day Mini',
    theme: 'sports',
    difficulty: 'easy',
    rows: 4,
    cols: 4,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 1,
        answer: 'HOW',
        text: 'Tactic analysis query when studying winning plays',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 1,
        col: 0,
        answer: 'HASH',
        text: 'Field yard markers painted on American gridirons',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'OSLO',
        text: 'Nordic capital that hosted the 1952 Winter Olympics',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 3,
        col: 0,
        answer: 'WHO',
        text: 'The reigning MVP or championship trophy holder',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 1,
        col: 0,
        answer: 'HOW',
        text: 'Manner in which a spectacular strike was delivered',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 1,
        answer: 'HASH',
        text: 'Gridiron yard boundary lines where the ball is spotted',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'OSLO',
        text: 'Historic winter venue with famous Holmenkollen ski jump',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 3,
        answer: 'WHO',
        text: 'Star athlete taking the final buzzer-beating shot',
      },
    ],
  },
  {
    id: 'pop-easy-1',
    title: 'Cinema & Sound',
    theme: 'pop-culture',
    difficulty: 'easy',
    rows: 4,
    cols: 4,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 1,
        answer: 'WIT',
        text: 'Sharp satirical banter in comedy films and sit-coms',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 1,
        col: 0,
        answer: 'WIRE',
        text: 'Iconic Baltimore crime drama television masterpiece (The ___)',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'IRON',
        text: 'Marvel armored hero portrayed by Robert Downey Jr. (___ Man)',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 3,
        col: 0,
        answer: 'TEN',
        text: 'Monumental 1991 grunge debut album by Pearl Jam',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 1,
        col: 0,
        answer: 'WIT',
        text: 'Clever humorous repartee penned by acclaimed playwrights',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 1,
        answer: 'WIRE',
        text: 'Studio microphone lead or legendary police wiretap show',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'IRON',
        text: 'Westeros royal throne forged by dragon flame',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 3,
        answer: 'TEN',
        text: 'Top 10 Billboard music countdown tier',
      },
    ],
  },

  // ==========================================
  // MEDIUM TIER (5x5 Pinwheel Crosswords)
  // ==========================================
  {
    id: 'science-med-1',
    title: 'Silicon & Orbit',
    theme: 'science',
    difficulty: 'medium',
    rows: 5,
    cols: 5,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'BASE',
        text: 'Alkaline substance with pH greater than 7 or binary radix',
      },
      {
        id: '3A',
        number: 3,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'SPACE',
        text: 'The cosmic expanse beyond Earth planetary atmosphere',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 4,
        col: 1,
        answer: 'TEST',
        text: 'Scientific experiment or automated unit validation suite',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'BUS',
        text: 'Internal hardware pathway carrying data between CPU and RAM',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'SCALE',
        text: 'Measurement ratio or logarithmic Richter magnitude index',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 2,
        col: 4,
        answer: 'EAT',
        text: 'Consume chemical nutrients to sustain metabolic life',
      },
    ],
  },
  {
    id: 'geography-med-1',
    title: 'Earth & Odyssey',
    theme: 'geography',
    difficulty: 'medium',
    rows: 5,
    cols: 5,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'ECHO',
        text: 'Acoustic wave reflection bouncing across mountain canyons',
      },
      {
        id: '3A',
        number: 3,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'EARTH',
        text: 'Third planet from the Sun and human global home',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 4,
        col: 1,
        answer: 'LEAD',
        text: 'Heavy mineral deposit or guide a pathfinder expedition',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'EYE',
        text: 'Calm center of a spinning tropical oceanic hurricane',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'HORSE',
        text: 'Wild mustang galloping across open prairie grassland',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 2,
        col: 4,
        answer: 'HAD',
        text: 'Possessed historical territorial sovereign jurisdiction',
      },
    ],
  },
  {
    id: 'sports-med-1',
    title: 'Playmakers Arena',
    theme: 'sports',
    difficulty: 'medium',
    rows: 5,
    cols: 5,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'PLAY',
        text: 'Execute a rehearsed strategic move on the field',
      },
      {
        id: '3A',
        number: 3,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'ORBIT',
        text: 'Trajectory path of a soaring baseball or golf drive',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 4,
        col: 1,
        answer: 'IRON',
        text: 'Golf club category engineered for fairway approach shots',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'PRO',
        text: 'Elite athlete competing in top tier sports leagues',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'AMBER',
        text: 'Cautionary yellow flag or referee warning indicator',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 2,
        col: 4,
        answer: 'TAN',
        text: 'Sun-kissed complexion earned on outdoor training grounds',
      },
    ],
  },
  {
    id: 'pop-med-1',
    title: 'Stage & Stardom',
    theme: 'pop-culture',
    difficulty: 'medium',
    rows: 5,
    cols: 5,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'BEST',
        text: 'Prestigious award category prefix: ___ Picture or Actor',
      },
      {
        id: '3A',
        number: 3,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'SPACE',
        text: 'Setting of classic sci-fi franchises Star Wars and Trek',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 4,
        col: 1,
        answer: 'STAR',
        text: 'Celebrated Hollywood idol immortalized on the Walk of Fame',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'BUS',
        text: 'Tour vehicle carrying rock bands on cross-country tours',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'SMART',
        text: 'Clever protagonist archetype in mystery detective cinema',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 2,
        col: 4,
        answer: 'EAR',
        text: 'Aesthetic musical sense for catching pitch and melodic harmony',
      },
    ],
  },
  {
    id: 'general-med-1',
    title: 'Beacon of Logic',
    theme: 'general',
    difficulty: 'medium',
    rows: 5,
    cols: 5,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'OSLO',
        text: 'European capital home to the Nobel Peace Prize ceremonies',
      },
      {
        id: '3A',
        number: 3,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'LOGIC',
        text: 'Rational deduction and consistent philosophical reasoning',
      },
      {
        id: '5A',
        number: 5,
        direction: 'across',
        row: 4,
        col: 1,
        answer: 'STAR',
        text: 'Beacon shining in darkness or five-point rating symbol',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'OIL',
        text: 'Viscous lubricant or midnight fuel burned while studying',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'LIGHT',
        text: 'Electromagnetic illumination revealing hidden truths',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 2,
        col: 4,
        answer: 'CAR',
        text: 'Wheeled passenger automobile used for daily transit',
      },
    ],
  },

  // ==========================================
  // HARD TIER (7x7 Symmetrical Crosswords)
  // ==========================================
  {
    id: 'pop-hard-1',
    title: 'Stage, Screen & Mystery',
    theme: 'pop-culture',
    difficulty: 'hard',
    rows: 7,
    cols: 7,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'QUANTUM',
        text: 'James Bond action blockbuster: ___ of Solace',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'ACTRESS',
        text: 'Female performer portraying dramatic characters on screen',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 4,
        col: 0,
        answer: 'THEATRE',
        text: 'Broadway or West End venue for live performing arts',
      },
      {
        id: '8A',
        number: 8,
        direction: 'across',
        row: 6,
        col: 0,
        answer: 'MYSTERY',
        text: 'Genre of Agatha Christie whodunits and thrilling cinema',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'QUANTUM',
        text: 'Subatomic physics realm featured in Marvel cinematic plots',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'ACTRESS',
        text: 'Leading lady celebrated with Oscar and BAFTA statuettes',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 4,
        answer: 'THEATRE',
        text: 'Proscenium hall hosting classic musicals and drama',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 6,
        answer: 'MYSTERY',
        text: 'Enigmatic puzzle plot loaded with clever twists',
      },
    ],
  },
  {
    id: 'science-hard-1',
    title: 'Quantum Atomics',
    theme: 'science',
    difficulty: 'hard',
    rows: 7,
    cols: 7,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'QUANTUM',
        text: 'Discrete packets of energy governed by Planck constant',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'ATOMICS',
        text: 'Branch of physical science studying subatomic particle nuclei',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 4,
        col: 0,
        answer: 'TRIBUTE',
        text: 'Honoring historical pioneers like Marie Curie and Einstein',
      },
      {
        id: '8A',
        number: 8,
        direction: 'across',
        row: 6,
        col: 0,
        answer: 'MYSTERY',
        text: 'Unsolved cosmological questions like dark matter and energy',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'QUANTUM',
        text: 'State of superposition and entanglement in computing',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'ATOMICS',
        text: 'Properties of isotopes, protons, and neutron interactions',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 4,
        answer: 'TRIBUTE',
        text: 'Memorial symposium honoring landmark scientific breakthroughs',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 6,
        answer: 'MYSTERY',
        text: 'Enigma of the cosmic wave function collapse',
      },
    ],
  },
  {
    id: 'general-hard-1',
    title: 'Masters of Theater',
    theme: 'general',
    difficulty: 'hard',
    rows: 7,
    cols: 7,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'QUANTUM',
        text: 'Significant transformative leap or revolutionary advance',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'ACTRESS',
        text: 'Celebrated performer on the legitimate dramatic stage',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 4,
        col: 0,
        answer: 'THEATRE',
        text: 'Cultural center for classical tragedy and witty comedy',
      },
      {
        id: '8A',
        number: 8,
        direction: 'across',
        row: 6,
        col: 0,
        answer: 'MASTERS',
        text: 'Individuals demonstrating supreme virtuosity in their craft',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'QUANTUM',
        text: 'Indivisible elementary unit of physical reality',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'ACTRESS',
        text: 'Thespian delivering Shakespearean monologues',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 4,
        answer: 'THEATRE',
        text: 'Palace of fine arts exhibiting opera and ballet',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 6,
        answer: 'MASTERS',
        text: 'Scholars possessing profound expertise and wisdom',
      },
    ],
  },
  {
    id: 'sports-hard-1',
    title: 'Championship Arena',
    theme: 'sports',
    difficulty: 'hard',
    rows: 7,
    cols: 7,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'ACTRESS',
        text: 'Thespian athlete performing synchronized acrobatic theater',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'TROPICS',
        text: 'Equatorial regions hosting sun-drenched beach sports',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 4,
        col: 0,
        answer: 'EPISODE',
        text: 'Memorable sports documentary chapter or highlight event',
      },
      {
        id: '8A',
        number: 8,
        direction: 'across',
        row: 6,
        col: 0,
        answer: 'SYSTEMS',
        text: 'Tactical formations like tiki-taka or full-court press',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'ACTRESS',
        text: 'Stage artist excelling in physical movement and poise',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'TROPICS',
        text: 'Warm maritime zones famed for sailing regattas',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 4,
        answer: 'EPISODE',
        text: 'Thrilling chapter in a multi-game playoff series',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 6,
        answer: 'SYSTEMS',
        text: 'Coaching playbooks coordinating team movement',
      },
    ],
  },
  {
    id: 'geography-hard-1',
    title: 'Wanderlust Atlas',
    theme: 'geography',
    difficulty: 'hard',
    rows: 7,
    cols: 7,
    clues: [
      {
        id: '1A',
        number: 1,
        direction: 'across',
        row: 0,
        col: 0,
        answer: 'QUANTUM',
        text: 'Leap across continents via supersonic transoceanic flight',
      },
      {
        id: '4A',
        number: 4,
        direction: 'across',
        row: 2,
        col: 0,
        answer: 'ATOMICS',
        text: 'Subterranean mineral testing in remote desert proving grounds',
      },
      {
        id: '6A',
        number: 6,
        direction: 'across',
        row: 4,
        col: 0,
        answer: 'TRIBUTE',
        text: 'Historic monument honoring legendary circumnavigators',
      },
      {
        id: '8A',
        number: 8,
        direction: 'across',
        row: 6,
        col: 0,
        answer: 'MASTERS',
        text: 'Cartographic guild cartographers mapping new worlds',
      },
      {
        id: '1D',
        number: 1,
        direction: 'down',
        row: 0,
        col: 0,
        answer: 'QUANTUM',
        text: 'Expedition milestone marking a daring polar crossing',
      },
      {
        id: '2D',
        number: 2,
        direction: 'down',
        row: 0,
        col: 2,
        answer: 'ATOMICS',
        text: 'Geological dating of ancient rock strata and fossils',
      },
      {
        id: '3D',
        number: 3,
        direction: 'down',
        row: 0,
        col: 4,
        answer: 'TRIBUTE',
        text: 'Memorial landmark erected at the edge of the world',
      },
      {
        id: '4D',
        number: 4,
        direction: 'down',
        row: 0,
        col: 6,
        answer: 'MASTERS',
        text: 'Seasoned maritime navigators steering by the stars',
      },
    ],
  },
];
